In [1]:
   import torch                                             # load PyTorch
   device = "cuda" if torch.cuda.is_available() else "cpu"  # use the GPU if there is one, otherwise the CPU
   print(device)                                            # should print cuda

cuda


1.Create a random tensor with shape (7, 7). Store it in a variable and print it, along with its shape.

In [3]:
t1 = torch.rand(7,7)
print(t1 , t1.shape)

tensor([[0.8838, 0.2054, 0.7448, 0.0142, 0.4322, 0.1150, 0.8989],
        [0.4480, 0.6286, 0.8484, 0.3767, 0.5488, 0.6642, 0.5967],
        [0.3205, 0.5326, 0.0369, 0.6560, 0.6501, 0.0112, 0.6730],
        [0.4417, 0.7903, 0.7186, 0.1289, 0.8295, 0.5423, 0.8788],
        [0.1114, 0.0078, 0.5330, 0.7571, 0.5458, 0.8641, 0.3420],
        [0.3475, 0.6931, 0.5343, 0.7055, 0.2415, 0.4527, 0.9626],
        [0.3368, 0.3805, 0.6479, 0.8236, 0.2594, 0.8736, 0.8216]]) torch.Size([7, 7])


Create another random tensor with shape (1, 7), then matrix multiply it with t1 from Exercise 2.


In [6]:
t2 = torch.rand(1,7)
# print(t1 @ t2)
# it gives error shape mus be in form of a*b b*c
t3 = t2.T
print(t1 @ t3)

tensor([[1.5439],
        [1.7395],
        [1.0183],
        [1.9499],
        [1.3925],
        [1.7310],
        [1.9391]])


Exercise 4

Set the random seed to 0, then do Exercises 2 and 3 again: create the (7, 7) tensor, create the (1, 7) tensor, and matrix multiply them.

Think first:

Where does the seed line go, before or after creating the tensors? (Topic 29)
Run the cell twice. Should you get the same result both times?

In [7]:
torch.manual_seed(0)        # set the seed to 0 BEFORE creating the random tensors

t1 = torch.rand(7, 7)       # create a 7x7 random tensor (same numbers every run)
t2 = torch.rand(1, 7)       # create a 1x7 random tensor (continues reading list 0)

result = t1 @ t2.T          # (7, 7) @ (7, 1): transpose t2 so the inner numbers match
print(result)               # display the result
print(result.shape)         # torch.Size([7, 1])

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


**Question:** `torch.manual_seed()` sets the random seed for the CPU. Is there a GPU equivalent? If there is, set the GPU random seed to 1234.


In [8]:
# Yes. The CPU and the GPU each have their own random numbers, so each has its own seed function. `torch.cuda.manual_seed()` sets the seed for the GPU.
torch.cuda.manual_seed(1234)    # set the seed for the GPU's random numbers to 1234
print(torch.cuda.initial_seed()) # check the GPU seed that is currently set

1234


6. Create two random tensors of shape (2, 3) and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors.

In [9]:
torch.manual_seed(1234)
a = torch.rand(2,3)
torch.manual_seed(1234)
b = torch.rand(2,3)

a = a.to(device)          # move a to the GPU and store it back
b = b.to(device)          # move b to the GPU and store it back

print(a)                  # display a (should show device='cuda:0')
print(b)                  # display b (should show device='cuda:0')

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


7. Do a matrix multiplication on a and b from Exercise 6

In [12]:
multi = a @ b.T
print(multi)
print(multi.shape)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')
torch.Size([2, 2])


8.Find the maximum and minimum values of the output from Exercise 7 (multi).

In [15]:
max_value = multi.max()       # the highest value in the result
min_value = multi.min()       # the lowest value in the result
print(max_value, min_value)   # display both

tensor(0.6287, device='cuda:0') tensor(0.2161, device='cuda:0')


9. Find the positions (indexes) of the maximum and minimum values in multi.

In [16]:
max_position = torch.argmax(multi)
min_position = torch.argmin(multi)
print(max_position , min_position)

tensor(3, device='cuda:0') tensor(1, device='cuda:0')


Set the seed to 0. Create a random tensor with shape (1, 1, 1, 10). Then make a new tensor with all the size-1 dimensions removed, leaving shape (10). Print:

the first tensor and its shape
the second tensor and its shape

In [17]:
torch.manual_seed(0)
t1 = torch.rand(1,1,1,10)
squeeze = torch.squeeze(t1)
print(t1 , t1.shape)
print(squeeze, squeeze.shape)

tensor([[[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
           0.4556, 0.6323]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
        0.6323]) torch.Size([10])
