In [1]:
import torch

Manipulating tensors

- `+ - * /` with a single number apply the operation to every element
- The result is a new tensor; the original is unchanged
- Store it back to keep the change: `x = x + 10`
- Division always gives float results, even for whole-number tensors
- Function versions: `torch.add`, `torch.sub`, `torch.mul`, `torch.div`
- Tensor with tensor works position by position (same shape needed)

Start with: marks = torch.tensor([45, 60, 72, 38])

Q1. Add 5 grace marks to every student. Print the result.

Q2. These marks are out of 80. Convert them to percentages (marks ÷ 80 × 100). What's the dtype of the result, and why?

Q3. Do Q1 again using torch.add, and double every mark using torch.mul.

Q4. Add 5 grace marks so that marks itself is updated. Print marks to confirm it changed.

In [4]:
marks = torch.tensor([45, 60, 72, 38])
print(marks + 5)
print(torch.add(marks,5))

print(((marks / 80)*100))

print(torch.mul(marks,2))

marks = marks + 5
print(marks)


tensor([50, 65, 77, 43])
tensor([50, 65, 77, 43])
tensor([56.2500, 75.0000, 90.0000, 47.5000])
tensor([ 90, 120, 144,  76])
tensor([50, 65, 77, 43])


Block 1: What is matrix multiplication?

- Element-wise (`*`): multiply matching positions and keep them separate
- Matrix multiplication: multiply matching pairs, then add them all up
- For two vectors this is called the dot product and gives a single number
- Write it as `torch.matmul(a, b)` or `a @ b`
- A neuron's weighted sum (inputs x weights, added up) is a dot product
- Matrix multiplication is the core operation of deep learning
- `torch.matmul` is much faster than a Python for loop

Practice (Block 1)

Q1. Your cart has prices [50, 30, 20, 100] and quantities [1, 4, 2, 1]. Print the cost of each item (element-wise) and the total bill (with @). Check the total by hand.

Q2. A neuron has inputs [2, 3], weights [4, 5] and bias 1. Calculate inputs @ weights + bias. Work it out by hand first, then check with code.

Q3. Try torch.matmul on two vectors of different lengths, such as [1, 2, 3] and [1, 2]. What happens, and why do you think it fails?

In [ ]:
price = torch.tensor([50,30,20,100])
quantity = torch.tensor([1,4,2,1])
print(price * quantity)
print(torch.matmul(price,quantity))
print(price @ quantity)

inputt = torch.tensor([2,3])
weights = torch.tensor([4,5])
bias = 1
print((inputt @ weights) + bias)

mat1 = torch.tensor([1,2,3])
print(mat1.shape)
mat2 = torch.tensor([1,2])
print(mat2.shape)
#print(torch.matmul(mat1,mat2)) # fails: the vectors have different lengths


tensor([ 50, 120,  40, 100])
tensor(310)
tensor(310)
tensor(33)
torch.Size([3])
torch.Size([2])


 Matrix x matrix

- Each result value = one row of the first matrix dot one column of the second
- Result at [row i, column j] = row i of A dot column j of B
- (a x b) @ (b x c) gives an (a x c) result
- Element-wise `*` and matrix multiplication `@` give different results
- Matrix multiplication usually gives a different result if you swap the order

Q1. Work out by hand: [[1, 2], [3, 4]] @ [[5, 6], [7, 8]]. Then check with code.

Q2. Using the same two matrices, is A @ B the same as B @ A? Try both.

Q3. Compare A * B (element-wise) with A @ B for the same matrices. Why are the answers different?

Q4. A third customer buys [0, 2, 1]. Add them as a third row of quantity. Predict the result's shape first, then calculate all the bills.

In [9]:

t1 = torch.tensor([[1, 2], [3, 4]])  # create the first 2x2 matrix
t2 = torch.tensor([[5, 6], [7, 8]])  # create the second 2x2 matrix
print(t1.shape)                      # shape of the first matrix
print(t2.shape)                      # shape of the second matrix

print(t1 @ t2)                       # rows of t1 dot columns of t2
print(t2 @ t1)                       # rows of t2 dot columns of t1 (different result)
print(t1 * t2)                       # element-wise: matching positions only, no adding up

# Q4: add a third customer
quantity = torch.tensor([[2, 1, 3],
                         [1, 0, 2],
                         [0, 2, 1]])  # quantities: 3 customers x 3 items
prices = torch.tensor([[10, 12],
                       [20, 18],
                       [30, 25]])     # prices: 3 items x 2 shops
bill = quantity @ prices             # each customer's total bill at each shop
print(bill)                          # display the bills
print(bill.shape)                    # size of the result: 3 customers x 2 shops



torch.Size([2, 2])
torch.Size([2, 2])
tensor([[19, 22],
        [43, 50]])
tensor([[23, 34],
        [31, 46]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[130, 117],
        [ 70,  62],
        [ 70,  61]])
torch.Size([3, 2])


The 2 shape rules

- Rule 1: the inner dimensions must match: (a x b) @ (b x c)
- Rule 2: the result has the outer dimensions: (a x c)
- A mismatch gives: `RuntimeError: mat1 and mat2 shapes cannot be multiplied`
- Always check the two shapes side by side before using `@`
- Shape mismatches are the most common error in deep learning

For each one, predict the result shape, or "error", first. Then check it using torch.rand and .shape.

Q1. (4×3) @ (3×5)

Q2. (5×2) @ (5×2)

Q3. (1×6) @ (6×1)

Q4. (6×1) @ (1×6)

Q5. (2×3) @ (2×3) should give an error. Can you think of a way to fix it by changing one of the matrices?

In [11]:
#prediction
# 4 * 5
# error
# 1 * 1
# 6 * 6
# error
# so instead of checking every example i check only 1

t1 = torch.rand(4,3)
t2 = torch.rand(3,5)
print(t1 @ t2)
print((t1 @ t2).shape)


t3 = torch.rand(2,3)
t4 = torch.rand(2,3)
#print(torch.matmul(t3,t4))


tensor([[0.6939, 0.4080, 1.0903, 0.7517, 0.2809],
        [0.4107, 0.3739, 0.6655, 0.1456, 0.2591],
        [0.7167, 0.3744, 1.0125, 0.5961, 0.3435],
        [0.8748, 0.6387, 1.4090, 0.7082, 0.4286]])
torch.Size([4, 5])


Transpose

- Transpose swaps rows and columns: a (2 x 3) becomes (3 x 2)
- Write it as `x.T` or `torch.transpose(x, 0, 1)`
- Use it to fix shape errors: (2 x 3) @ (2 x 3) fails, (2 x 3) @ (3 x 2) works
- `.T` does not change the original tensor
- Transposing twice gives back the original
- Neural network layers compute `inputs @ weights.T + bias`

Q1. Create A = torch.tensor([[1, 2], [3, 4], [5, 6]]). Predict A.T and its shape, then check.

Q2. Fix Block 3's Q5: t3 = torch.rand(2, 3) and t4 = torch.rand(2, 3). Make both t3 @ t4.T and t3.T @ t4 work. Predict each result's shape first.

Q3. What is A.T.T (transposing twice)? Predict, then check.

Q4. By hand: torch.tensor([[1, 0, 2]]) @ torch.tensor([[3, 1, 1]]).T. What shape and what value? Then check with code.

In [13]:
A = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(A.T)
print((A.T).shape)

t3 = torch.rand(2, 3)
t4 = torch.rand(2, 3)
print(t3.T @ t4)
print(t3 @ t4.T)

print((A.T).T)

print(torch.tensor([[1, 0, 2]]) @ torch.tensor([[3, 1, 1]]).T)

tensor([[1, 3, 5],
        [2, 4, 6]])
torch.Size([2, 3])
tensor([[0.3209, 0.4160, 0.7088],
        [0.5349, 0.4071, 0.7026],
        [0.1203, 0.0156, 0.0309]])
tensor([[0.2433, 0.5960],
        [0.4883, 0.5157]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[5]])


Min, max, sum and mean

- `x.min()`, `x.max()`, `x.sum()`, `x.mean()` reduce a tensor to one number
- Function versions: `torch.min(x)`, `torch.max(x)`, `torch.sum(x)`, `torch.mean(x)`
- `mean` needs a float tensor; on int64 it fails with a dtype error
- Fix: convert first with `x.type(torch.float32).mean()`
- The results are one-number tensors; `.item()` gives a plain number

A week's temperatures: temps = torch.tensor([31, 29, 35, 33, 30, 28, 34])

Q1. Find the hottest day's temperature, the coldest, and the total of all seven.

Q2. Find the average temperature. First try temps.mean() directly and see what happens, then fix it.

Q3. Do Q1 and Q2 again using the function versions (torch.max, torch.min, torch.sum, torch.mean).

Q4. Print the average as a plain Python number using .item().

In [20]:
temps = torch.tensor([31, 29, 35, 33, 30, 28, 34])  # create a tensor of a week's temperatures

hottest_day = temps.max()                  # highest temperature of the week
print(hottest_day)                         # display the highest temperature
coldest_day = torch.min(temps)             # lowest temperature, using the function version
print(coldest_day)                         # display the lowest temperature
print(temps.sum())                         # total of all seven temperatures

# print(temps.mean())                      # fails: mean needs a float tensor
print(temps.type(torch.float32).mean())    # convert to float, then find the average
print(temps.type(torch.float32).mean().item())  # average as a plain Python number


tensor(35)
tensor(28)
tensor(220)
tensor(31.4286)
31.428571701049805


Other names for the same thing

- `torch.mm(A, B)` = matrix multiplication for 2-D matrices only; errors on vectors
- `torch.matmul(A, B)` and `A @ B` work on vectors and matrices
- `torch.multiply(x, y)` = `torch.mul(x, y)` = `x * y` (element-wise)
- `torch.float` = float32, `torch.half` = float16, `torch.double` = float64
- `torch.long` = int64 (error messages often say "Long")

### Catch-up Block 2: Integer datatypes

- Whole-number types: `int8`, `int16`, `int32`, `int64` (default, also called `torch.long`)
- More bits = bigger range and more memory
- `int8` holds -128 to 127; `uint8` holds 0 to 255 (common for pixel values)
- Numbers too big for the type wrap around silently, with no error
- Smaller types save memory (8-bit models are used on mobile devices)

### Catch-up Block 3: Timing code with %%time

- `%%time` on the first line of a notebook cell measures how long the cell takes
- `%time` (single %) times a single line
- "Wall time" is the real time you waited
- Magic commands work in notebooks (Jupyter, VS Code, Colab), not in .py files
- Python for loops over tensors are very slow; PyTorch operations like `@` are much faster

Positional min and max

- `x.argmax()` gives the position (index) of the largest value
- `x.argmin()` gives the position (index) of the smallest value
- Function versions: `torch.argmax(x)`, `torch.argmin(x)`
- Use the position to look up the value: `x[x.argmax()]`
- If the max appears more than once, the first position is returned
- Works on whole-number tensors (no float needed, unlike `mean`)
- Used in classification to turn scores into a predicted label

A week's temperatures, Monday to Sunday: temps = torch.tensor([31, 29, 35, 33, 30, 28, 34])

Q1. Find the position of the hottest day and the coldest day. Which days of the week are they?

Q2. Use the position from Q1 to get the hottest temperature back, like marks[marks.argmax()].

Q3. A model gives the scores torch.tensor([0.1, 0.6, 0.3]) for the labels ["cat", "dog", "bird"]. Use argmax to print the predicted label. (Hint: .item() turns the position into a plain number you can use with a Python list.)

Q4. Guess what torch.tensor([5, 9, 9, 2]).argmax() gives, then run it.

In [21]:
temps = torch.tensor([31, 29, 35, 33, 30, 28, 34])  # a week's temperatures, Monday to Sunday
hot_day = temps.max()                    # the highest temperature
cold_day = temps.min()                   # the lowest temperature

index_hot_day = torch.argmax(temps)      # position of the hottest day
index_cold_day = torch.argmin(temps)     # position of the coldest day
print(index_hot_day, index_cold_day)     # display both positions
print(temps[index_hot_day])              # use the position to look up the hottest temperature

scores = torch.tensor([0.1, 0.6, 0.3])   # model scores for each category
labels = ["cat", "dog", "bird"]          # the category names, in the same order
print(labels[scores.argmax().item()])    # turn the highest score's position into a label

print(torch.tensor([5, 9, 9, 2]).argmax())  # max appears twice, so the first position is returned

tensor(2) tensor(5)
tensor(35)
dog
tensor(1)


In [24]:
scores = torch.tensor([0.05, 0.15, 0.70, 0.10])  # the model's score for each fruit
labels = ["apple", "banana", "mango", "orange"]   # the fruit names, in the same order

max_score = torch.argmax(scores)
print(max_score)

python_number = max_score.item()
print(python_number)

print(labels[python_number])


tensor(2)
2
mango


reshape

- `x.reshape(new_shape)` rearranges the same numbers into a new shape
- The product of the new shape must equal the total number of items
- Numbers are filled in order, row by row
- A wrong size gives: `RuntimeError: shape '[5, 3]' is invalid for input of size 12`
- `reshape(1, n)` adds an extra dimension to a vector of n numbers
- `-1` in a shape means "work this size out automatically", e.g. `x.reshape(3, -1)`
- `x.reshape(-1)` flattens any tensor into one long row
- Only one `-1` is allowed, and the total must still divide evenly
- The original tensor keeps its shape; store the result to keep the new one

Start with: nums = torch.arange(1, 25) (that's 24 numbers)

Q1. Reshape nums into 4×6, 6×4 and 2×3×4. Predict each shape first, then check.

Q2. Which of these shapes work for 24 numbers: (5, 5), (8, 3), (2, 2, 6), (7, 3)? Predict, then try one that fails and read the error.

Q3. Use -1: reshape nums into (4, -1) and (-1, 3). Predict what number -1 becomes in each case, then check the shapes.

Q4. Take your 2×3×4 tensor from Q1 and flatten it back into one long row using -1. What's its shape?

Q5. Reshape torch.arange(10) into shape (1, 10). How many dimensions does it have now?

Q6. Try nums.reshape(-1, -1). What error do you get, and why?

Q7. After all the reshapes, print nums.shape. Did the original change?

In [28]:
nums = torch.arange(1, 25)      # create 24 numbers: 1 to 24

# Q1: reshape into different shapes (store each one, then check it)
grid_4x6 = nums.reshape(4, 6)   # 4 rows of 6
print(grid_4x6.shape)           # shape of the 4x6 version
grid_6x4 = nums.reshape(6, 4)   # 6 rows of 4
print(grid_6x4.shape)           # shape of the 6x4 version
cube = nums.reshape(2, 3, 4)    # 2 trays, each with 3 rows of 4
print(cube.ndim, cube.shape)    # dimensions and shape of the 3-D version

# Q2: 24 items: (8, 3) and (2, 2, 6) work; (5, 5) and (7, 3) don't
print(nums.reshape(8, 3).shape)     # 8 x 3 = 24, so it works
print(nums.reshape(2, 2, 6).shape)  # 2 x 2 x 6 = 24, so it works
# nums.reshape(5, 5)                # fails: 5 x 5 = 25, not 24

# Q3: let PyTorch work out the -1
print(nums.reshape(4, -1).shape)    # 4 rows; columns = 24 / 4
print(nums.reshape(-1, 3).shape)    # 3 columns; rows = 24 / 3

# Q4: flatten the 3-D tensor back into one row
flat = cube.reshape(-1)             # flatten into a single row
print(flat.shape)                   # shape of the flattened tensor

# Q5: add an extra dimension to a vector
row = torch.arange(10).reshape(1, 10)  # put 10 numbers inside 1 row
print(row.ndim, row.shape)          # dimensions and shape

# Q6: two unknowns are not allowed
# nums.reshape(-1, -1)              # fails: only one -1 can be worked out

# Q7: the original is unchanged
print(nums.shape)                   # shape of the original tensor


torch.Size([4, 6])
torch.Size([6, 4])
3 torch.Size([2, 3, 4])
torch.Size([8, 3])
torch.Size([2, 2, 6])
torch.Size([4, 6])
torch.Size([8, 3])
torch.Size([24])
2 torch.Size([1, 10])
torch.Size([24])


### Extra: dim in sum, mean, max and argmax

- Without `dim`, `sum` / `mean` / `max` / `argmax` work on the whole tensor
- `dim` is the dimension that disappears from the shape
- For a 2-D tensor: `dim=0` works down each column, `dim=1` works across each row
- `mean(dim=...)` still needs a float tensor
- `x.max(dim=...)` returns values and positions: use `.values` or `.indices`
- `dim` in PyTorch works like `axis` in NumPy

Rows = 3 shops, columns = 4 days (Mon, Tue, Wed, Thu):

python
sales = torch.tensor([[10, 20, 30, 40],
                      [15, 25, 35,  5],
                      [20, 10, 40, 30]])

Q1. Find the total sales per shop. Predict the result's shape first.

Q2. Find the total sales per day. Predict the shape first.

Q3. Find the average sales per shop. (Remember what mean needs.)

Q4. For each day, which shop sold the most? Use argmax. Which dim do you need?

In [9]:
sales = torch.tensor([[10, 20, 30, 40],
                      [15, 25, 35,  5],
                      [20, 10, 40, 30]])

total_sales = sales.sum(dim=1)
print(total_sales)

per_day_sales = sales.sum(dim=0)
print(per_day_sales)

avg_per_shop = sales.type(torch.float32).mean(dim=1)
print(avg_per_shop)



most_per_day = sales.argmax(dim=0)
print(most_per_day)
print(sales.max(dim=0).values)



tensor([100,  80, 100])
tensor([ 45,  55, 105,  75])
tensor([25., 20., 25.])
tensor([2, 1, 2, 0])
tensor([20, 25, 40, 40])


view

- `x.view(new_shape)` shows the same data in a new shape without copying
- A view is another name for the same data: change one and the other changes too
- `x.clone()` makes an independent copy (like NumPy's `.copy()`)
- Views are fast and save memory because nothing is copied
- Same shape rules as reshape: the total must match, and `-1` is allowed

**view vs reshape**
- `view` always shares data; if it can't, it gives an error
- `reshape` shares data when it can; otherwise it quietly makes a copy
- Use `reshape` by default; use `view` when you want a guaranteed shared-data result
- You will often see `view` in older code and tutorials

**Why view sometimes fails**
- A tensor's data is stored in memory as one long line; the shape is just a reading rule
- A view only changes the reading rule; it never moves the data
- After a transpose, the data is no longer in reading order (not contiguous)
- `view` fails on such tensors; `reshape` works by copying into a new order
- `x.is_contiguous()` checks whether the data is stored in reading order

Write all the code yourself.

Q1. Create a tensor holding 10, 20, 30, 40. Make a view of it with 2 rows and 2 columns. Using the view, change the number in row 1, column 1 to 0. Before printing, guess what the original tensor looks like now. Then print both tensors.

Q2. Repeat Q1, but this time make the view from an independent copy of the original. Guess the original again, then print both.

Q3. Using a tensor holding 10, 20, 30, 40, make a view with 2 columns and let PyTorch work out the number of rows. Print its shape.

Q4. Create the numbers 1 to 6 arranged as 2 rows and 3 columns. Transpose it. Check whether the transposed tensor is contiguous. Then try to flatten the transposed tensor into one row using view, and read the error. Finally, flatten it using the method that works.

In [ ]:
t1 =torch.tensor([10,20,30,40])
x = t1.view(2,2)
x[0,0] = 0
print(t1)
print(x)

t2 = torch.tensor([10,20,30,40])
x = t2.clone().view(2,2)
x[0,0] = 0
print(t2)
print(x)

t1 =torch.tensor([10,20,30,40])
x = t1.view(-1,2)
print(x.shape)

t3 = torch.tensor([1,2,3,4,5,6])
x = t3.reshape(2,3)
print(x.T)
y = t3.view(2,3)
print(y.T)


tensor([ 0, 20, 30, 40])
tensor([[ 0, 20],
        [30, 40]])
tensor([10, 20, 30, 40])
tensor([[ 0, 20],
        [30, 40]])
torch.Size([2, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


stack

- `torch.stack([a, b, c], dim=...)` joins tensors and creates a new dimension
- All tensors must have the same shape
- `dim=0`: tensors are placed one below the other (each becomes a row)
- `dim=1`: tensors are placed side by side (each becomes a column)
- Stacking N tensors of shape `[3]` gives `[N, 3]` with `dim=0` and `[3, N]` with `dim=1`
- The tensors go inside square brackets as a list

Q1. Create three tensors holding 3 days of temperatures for three cities: City A 30, 32, 31, City B 25, 27, 26, City C 35, 36, 34. Stack them with dim=0. Predict the shape first. What does each row stand for?

Q2. Stack the same three tensors with dim=1. Predict the shape. What does each row stand for now?

Q3. Stack City A's tensor with itself 4 times using dim=0. What's the shape?

Q4. Try stacking a tensor of 3 numbers with a tensor of 2 numbers. Read the error. Why does it fail?

In [ ]:
cityA = torch.tensor([30,32,31])
cityB = torch.tensor([25,27,26])
cityC = torch.tensor([35,36,34])

x = torch.stack([cityA, cityB, cityC], dim=0)
print(x)

y = torch.stack([cityA, cityB, cityC], dim=1)
print(y)


a = torch.stack([cityA, cityA, cityA, cityA], dim=0)
print(a)

# RuntimeError: stack expects each tensor to be equal size, but got [3] at entry 0 and [2] at entry 1

tensor([[30, 32, 31],
        [25, 27, 26],
        [35, 36, 34]])
tensor([[30, 25, 35],
        [32, 27, 36],
        [31, 26, 34]])
tensor([[30, 32, 31],
        [30, 32, 31],
        [30, 32, 31],
        [30, 32, 31]])


 squeeze

- A dimension of size 1 is extra wrapping: an extra bracket but no extra numbers
- `x.squeeze()` removes every dimension of size 1
- `x.squeeze(dim=0)` removes only that dimension, and only if its size is 1
- The numbers stay exactly the same; only the shape changes
- If there are no size-1 dimensions, nothing changes
- Useful for removing extra dimensions from model outputs

Q1. Create a tensor holding 5, 10, 15, 20 wrapped in an extra bracket, so its shape is [1, 4]. Squeeze it. Predict the new shape first.

Q2. Create a random tensor with shape (1, 1, 1, 10). Squeeze it. Predict the new shape.

Q3. Create a tensor of zeros with shape (1, 3, 1, 4). Predict its shape after squeezing, then check.

Q4. Create a tensor of ones with shape (2, 3) and squeeze it. What happens? Predict, then check.

In [34]:
t1 = torch.tensor([5,10,15,20])
print(t1.shape)
t2 = torch.tensor([[5,10,15,20]])
print(t2.shape)
t3 = torch.squeeze(t2)
print(t3)
print(t3.shape)

t4 = torch.rand([1,1,1,10])
print(t4)
print(torch.squeeze(t4), t4.shape)
t5 = torch.squeeze(t4)
print(torch.squeeze(t5), t5.shape)

t6 = torch.zeros(1,3,1,4)
print(t6.shape)
t7 = torch.squeeze(t6)
print(t7.shape)

t8 = torch.rand(2,3)
t9 = torch.squeeze(t8)
print(t9.shape)

#he function version torch.squeeze(x), which is the same as x.squeeze().

torch.Size([4])
torch.Size([1, 4])
tensor([ 5, 10, 15, 20])
torch.Size([4])
tensor([[[[0.1287, 0.3177, 0.9819, 0.7813, 0.6289, 0.2907, 0.5805, 0.5607,
           0.4194, 0.5440]]]])
tensor([0.1287, 0.3177, 0.9819, 0.7813, 0.6289, 0.2907, 0.5805, 0.5607, 0.4194,
        0.5440]) torch.Size([1, 1, 1, 10])
tensor([0.1287, 0.3177, 0.9819, 0.7813, 0.6289, 0.2907, 0.5805, 0.5607, 0.4194,
        0.5440]) torch.Size([10])
torch.Size([1, 3, 1, 4])
torch.Size([3, 4])
torch.Size([2, 3])


unsqueeze

- `x.unsqueeze(dim=...)` adds a dimension of size 1 (the opposite of squeeze)
- `dim` is the position where the new 1 is inserted in the shape
- For a vector `[n]`: `dim=0` gives `[1, n]` (a row), `dim=1` gives `[n, 1]` (a column)
- `dim` must be given, unlike squeeze
- The numbers stay the same; only the shape changes
- Common uses: adding a batch dimension (`dim=0`), one feature per sample (`dim=1`)

Q1. Create a tensor holding 5, 10, 15, 20. Unsqueeze it with dim=0. Predict the shape first, then print the tensor and its shape.

Q2. Do the same with dim=1. Predict the shape. Is the result a row or a column?

Q3. Create a random "image" with shape (3, 28, 28). Add a batch dimension at the front. Predict the new shape.

Q4. Create 50 house sizes with torch.arange(50), which has shape [50]. Turn it into shape [50, 1]. Which dim do you need?

Q5. Take your result from Q1 and squeeze it. Do you get the original shape back?

In [43]:
t1 = torch.tensor([5,10,15,20])
a = t1.unsqueeze(dim=0)
print(a.shape, a , t1.shape)
b = t1.unsqueeze(dim=1)
print(b.shape, b , t1.shape)

image = torch.rand(3,28,28)
batch = image.unsqueeze(dim=0)          # add a batch dimension at the front
print(batch.shape)

house = torch.rand(50)
house1 = torch.unsqueeze(house , dim=1)
print(house1.shape)

print(t1.squeeze().shape)
print(a.squeeze().shape)   # [1, 4] back to [4]


torch.Size([1, 4]) tensor([[ 5, 10, 15, 20]]) torch.Size([4])
torch.Size([4, 1]) tensor([[ 5],
        [10],
        [15],
        [20]]) torch.Size([4])
torch.Size([1, 3, 28, 28])
torch.Size([50, 1])
torch.Size([4])
torch.Size([4])


permute

- `x.permute(...)` reorders the dimensions of a tensor
- The numbers are the old positions, written in the new order you want
- `[height, width, colour]` to `[colour, height, width]` is `permute(2, 0, 1)`
- Each value stays with its correct row, column and channel
- `reshape` to the same shape scrambles the data; use `permute` to reorder dimensions
- For 2 dimensions, `permute(1, 0)` is the same as `.T`
- `permute` shares data with the original (like `view`)

Q1. Create a random image with shape (224, 224, 3) (height, width, colour). Permute it to colour-first. Predict the numbers inside permute(...) and the new shape.

Q2. Create a random tensor with shape (10, 20, 30). Predict the shape after permute(1, 2, 0), then check.

Q3. For the matrix [[1, 2, 3], [4, 5, 6]], compare permute(1, 0) with reshape(3, 2). Same shape, but are the values the same?

Q4. Start with a colour-first image of shape (3, 28, 28) and permute it back to (28, 28, 3). Which numbers go inside permute(...)?

In [47]:
# Q1: height-width-colour to colour-first
image = torch.rand(224, 224, 3)         # a random image: height, width, colour channels
colour_first = image.permute(2, 0, 1)   # new order: colour, height, width
print(image.shape, colour_first.shape)  # [224, 224, 3] and [3, 224, 224]

# Q2: reorder a 3-D tensor
t = torch.rand(10, 20, 30)              # a random tensor with shape [10, 20, 30]
print(t.permute(1, 2, 0).shape)         # new order: old 1, old 2, old 0

# Q3: permute vs reshape
m = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])           # 2 rows, 3 columns
print(m.permute(1, 0))                  # swap dimensions: each column stays together
print(m.reshape(3, 2))                  # pour numbers in order: columns get mixed

# Q4: colour-first back to height-width-colour
img = torch.rand(3, 28, 28)             # a colour-first image
print(img.permute(1, 2, 0).shape)       # new order: height, width, colour



torch.Size([224, 224, 3]) torch.Size([3, 224, 224])
torch.Size([20, 30, 10])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([28, 28, 3])


Picking a row or a single value

- `x[i]` selects row i; `x[i, j]` selects the value at row i, column j
- `x[i][j]` gives the same result as `x[i, j]`; the comma style is preferred
- Counting starts at 0
- Negative indexes count from the end: `x[-1]` is the last row
- Each index removes one dimension: `[3, 3]` to `[3]` to a single number
- `.item()` turns a single selected value into a plain Python number

Use this data. Rows are 4 shops, and columns are 3 days:

python
sales = torch.tensor([[10, 20, 30],
                      [15, 25, 35],
                      [20, 10, 40],
                      [ 5, 50, 45]])

Q1. Select all of shop 2's sales. Predict the shape first.

Q2. Select shop 3's sales on day 1. Do it both ways, with [i][j] and [i, j]. Predict the value first.

Q3. Select the last shop's row using a negative index.

Q4. Get shop 0's sales on day 2 as a plain Python number.

In [3]:
sales = torch.tensor([[10, 20, 30],
                      [15, 25, 35],
                      [20, 10, 40],
                      [ 5, 50, 45]])

sale_2 = sales[1]
print(sale_2)

sale_3_1 = sales[2,1]
print(sale_3_1)

last_shop = sales[-1]
print(last_shop)

sale_0 = sales[0,2]
print(sale_0.item())

tensor([15, 25, 35])
tensor(10)
tensor([ 5, 50, 45])
30


The colon

- `:` means "all" of that dimension
- `x[:, j]` selects column j (every row); `x[i, :]` selects row i (same as `x[i]`)
- `start:end` selects a range; the end is not included
- `1:` means from 1 to the end; `:2` means from the start up to 2
- A selected column comes out as a 1-D tensor (printed as a row)
- Negative indexes also work with `:`, e.g. `x[:, -1]` is the last column

Q1. Select every shop's sales on the 2nd day (index 1). Predict the values and the shape first.

Q2. Select every shop's sales on the last day, using a negative index.

Q3. Select all days for the shop at index 3, using :. Is the result the same as sales[3]?

Q4. Select the first two shops (index 0 and 1) for all days, using a range. Predict the shape.

Q5. Find the total sales on the 3rd day (index 2) across all shops. (Hint: select the column, then .sum().)

In [10]:
# rows = 4 shops, columns = 3 days
sales = torch.tensor([[10, 20, 30],
                      [15, 25, 35],
                      [20, 10, 40],
                      [ 5, 50, 45]])

print(sales[:, 1])         # all rows, column 1: every shop's sales on the 2nd day
print(sales[:, -1])        # all rows, last column: every shop's sales on the last day
print(sales[3, :])         # row index 3, all columns: same as sales[3], shape [3]
print(sales[3:])           # a range from index 3 to the end: keeps the dimension, shape [1, 3]
print(sales[:2, :])        # rows 0 and 1, all columns: the first two shops
print(sales[:, 2].sum())   # column 2 (3rd day) for every shop, then add them up



tensor([20, 25, 10, 50])
tensor([30, 35, 40, 45])
tensor([ 5, 50, 45])
tensor([[ 5, 50, 45]])
tensor([[10, 20, 30],
        [15, 25, 35]])
tensor(150)


Indexing 3-D tensors

- A 3-D tensor is indexed as `x[tray, row, column]`
- A single number picks one item and removes that dimension
- `:` keeps the whole dimension
- `x[0, 0, 0]` gives a single value; `x[0, 0]` gives a row; `x[0]` gives a whole tray
- `x[:, :, 1]` gives column 1 from every row of every tray
- Extra brackets in a result mean `:` kept a dimension of size 1

Part A: the course's own exercises (use x from above)

Q1. Index x to get the number 9.

Q2. Index x to get [3, 6, 9] (the last column).

Part B: a bigger tensor

python
y = torch.arange(1, 25).reshape(2, 3, 4)   # 2 trays, each 3 rows x 4 columns

(Print y first so you can see the numbers.)

Q3. Select the 2nd tray (index 1).

Q4. Select row index 0 from every tray. Predict the shape first.

Q5. Select the number 20. Work out its tray, row and column first.

Q6. Select column index 2 from every tray and every row. Predict the shape first.

In [20]:
x = torch.arange(1, 10).reshape(1, 3, 3)  # the numbers 1 to 9 as 1 tray of 3 rows x 3 columns
print(x)                                  # display it

print(x[:,2,2])
print(x[:,:,2])
print(x[:,1])
print(x[:,:,0])

y = torch.arange(1, 25).reshape(2, 3, 4)  # 2 trays, each 3 rows x 4 columns

print(y[1])         # Q3: pick tray 1: the whole 2nd tray
print(y[:, 0])      # Q4: all trays, row 0: the first row of each tray
print(y[1, 1, 3])   # Q5: tray 1, row 1, column 3: the number 20
print(y[:, :, 2])   # Q6: all trays, all rows, column 2


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([9])
tensor([[3, 6, 9]])
tensor([[4, 5, 6]])
tensor([[1, 4, 7]])
tensor([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])
tensor([[ 1,  2,  3,  4],
        [13, 14, 15, 16]])
tensor(20)
tensor([[ 3,  7, 11],
        [15, 19, 23]])
