In [3]:
%pip install torch

  Using cached setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.5/124.1 MB 479.2 kB/s eta 0:04:18
   ---------------------------------------- 0.5/124.1 MB 479.2 kB/s eta 0:04:18
   ---------------------------------------- 0.5/124.1 MB 479.2 kB/s eta 0:04:18
   ---------------------------------------- 0.8/124.1 MB 466.0 kB/s eta 0:04:25
   ---------------------------------------- 0.8/124.1 MB 466.0 kB/s eta 0:04:25
   ---------------------------------------- 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
import torch # load PyTorch
print(torch.__version__)

2.14.0+cpu


In [9]:
scalar = torch.tensor(7)  # create a tensor holding a single number (a scalar)
print(scalar)             # display the tensor
print(scalar.ndim)        # number of dimensions of the tensor
print(scalar.shape)       # size along each dimension (an attribute, so no brackets)
print(scalar.size())      # same as .shape, but written as a method with brackets

tensor(7)
0
torch.Size([])
torch.Size([])


In [5]:
vector = torch.tensor([10,20,30]) # create a tensor holding a list of numbers (a vector)
print(vector) 
print(vector.ndim) # number of dimensions of the tensor
print(vector.shape)  # size along each dimension (an attribute, so no brackets)
print(vector.size()) # same as .shape, but written as a method with brackets

tensor([10, 20, 30])
1
torch.Size([3])
torch.Size([3])


In [6]:
matrix = torch.tensor([[1,2,3],[3,4,5]]) # create a tensor holding a list of lists (a matrix)
print(matrix)
print(matrix.ndim) # number of dimensions of the tensor
print(matrix.shape)  # size along each dimension (an attribute, so no brackets)
print(matrix.size()) # same as .shape, but written as a method with brackets

tensor([[1, 2, 3],
        [3, 4, 5]])
2
torch.Size([2, 3])
torch.Size([2, 3])


In [9]:
matrixx = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # create a tensor holding a list of lists (a matrix)
print(matrixx)
print(matrixx[0]) # access the first row of the matrix
print(matrixx[0].ndim) # number of dimensions of the tensor
print(matrixx[0].shape)  # size along each dimension (an attribute, so no brackets
print(matrixx[0][1])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
1
torch.Size([3])
tensor(2)


In [10]:
# create a 3-D tensor: 2 trays, each with 2 rows and 3 columns
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])
print(TENSOR)        # display the tensor
print(TENSOR.ndim)   # number of dimensions of the tensor
print(TENSOR.shape)  # size along each dimension (trays, rows, columns)
print(TENSOR[0])     # select the first tray

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [12]:
rand_tensor = torch.rand(3,4) # create a 3x4 tensor filled with random numbers between 0 and 1
print(rand_tensor) # 
print(rand_tensor.ndim) 
print(rand_tensor.shape)

tensor([[0.0460, 0.0848, 0.9404, 0.8211],
        [0.8303, 0.7819, 0.5297, 0.0974],
        [0.8267, 0.0192, 0.5485, 0.4467]])
2
torch.Size([3, 4])


In [16]:
ran_matrix = torch.rand(2,5)
print(ran_matrix)
print(ran_matrix.ndim)         # number of dimensions of the tensor
print(ran_matrix.shape)

rand_vector = torch.rand(6)
print(rand_vector)
print(rand_vector.ndim)         # number of dimensions of the tensor
print(rand_vector.shape)        # size along each dimension

rand_3d = torch.rand(2,3,4)
print(rand_3d)
print(rand_3d.ndim)             # number of dimensions of the tensor
print(rand_3d.shape) 

tensor([[0.3812, 0.6005, 0.1381, 0.7532, 0.4516],
        [0.8876, 0.0795, 0.3678, 0.9117, 0.8453]])
2
torch.Size([2, 5])
tensor([0.2921, 0.2712, 0.4086, 0.8786, 0.5583, 0.6125])
1
torch.Size([6])
tensor([[[0.6245, 0.6264, 0.9714, 0.1833],
         [0.2652, 0.8430, 0.3831, 0.0902],
         [0.1175, 0.0138, 0.4328, 0.0649]],

        [[0.9596, 0.4655, 0.5804, 0.5577],
         [0.1506, 0.4487, 0.5856, 0.4879],
         [0.7701, 0.5655, 0.0897, 0.7600]]])
3
torch.Size([2, 3, 4])


Q1. Create a random colour image 32 pixels high and 32 wide, using size=. Check its ndim and shape. How many numbers does it hold in total?

Q2. Create a random grayscale image that's 28 pixels high and 28 wide. What's its shape?

Q3. Create the same 32 × 32 colour image from Q1, but with the colours first. What do you write inside size=(...)?

In [17]:
# Q1: colour image, 32 high x 32 wide
image = torch.rand(size=(32, 32, 3))            # create a random colour image: height, width, colour channels
print(image.ndim)                               # number of dimensions of the tensor
print(image.shape)                              # size along each dimension

# Q2: grayscale image, 28 x 28
grayscale_image = torch.rand(size=(28, 28, 1))  # create a random grayscale image: 1 brightness number per pixel
print(grayscale_image.ndim)                     # number of dimensions of the tensor
print(grayscale_image.shape)                    # size along each dimension

# Q3: colour image with colours first
image_cf = torch.rand(size=(3, 32, 32))         # create a random colour image: colour channels, height, width
print(image_cf.shape)                           # size along each dimension

3
torch.Size([32, 32, 3])
3
torch.Size([28, 28, 1])
torch.Size([3, 32, 32])


Q1. Create a tensor of zeros with 2 rows and 3 columns. Check its shape.

Q2. Create a tensor of ones shaped like a tiny colour image: 4 high, 4 wide, 3 colours. How many ones does it hold in total?

Q3. Create a random 2 × 3 tensor and multiply it by a 2 × 3 tensor of ones. Compare the result with the original random tensor. What do you notice?

In [22]:
zero_tensor = torch.zeros(2, 3)          # create a 2x3 tensor filled with zeros
print(zero_tensor)                       # display the zeros tensor
print(zero_tensor.shape)                 # size along each dimension

one_tensor = torch.ones(size=(4, 4, 3))  # create a 4x4x3 tensor filled with ones
print(one_tensor)                        # display the ones tensor

rand1_tensor = torch.rand(3, 2)          # create a 3x2 tensor of random numbers
rand2_tensor = torch.rand(3, 2)          # create another 3x2 tensor of random numbers (same shape)
print(rand1_tensor * rand2_tensor)       # multiply each number by the number in the same slot of the other tensor

ones_tensor = torch.ones(3, 2)           # create a 3x2 tensor of ones (same shape)
print(rand1_tensor)                      # display the original random tensor
print(rand1_tensor * ones_tensor)        # multiply each number by 1, leaving it unchanged

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[0.1134, 0.3566],
        [0.0198, 0.0243],
        [0.0358, 0.0097]])
tensor([[0.3649, 0.6389],
        [0.0771, 0.9604],
        [0.6805, 0.1374]])
tensor([[0.3649, 0.6389],
        [0.0771, 0.9604],
        [0.6805, 0.1374]])


 `torch.arange(start, end, step)` creates a 1-D tensor of evenly spaced numbers
- **start**: the first number (default is 0)
- **end**: where to stop; this number is **not included**
- **step**: the jump between numbers (default is 1)
- Giving only one number sets `end`, and counting starts from 0
- To include the last number, set `end` just above it
- The result is always a vector (1-D)
- Whole-number inputs give whole numbers; decimal inputs give decimals
- `torch.range` is outdated; always use `torch.arange`

Q1. Create roll numbers from 1 to 30, with 30 included. Check the shape.

Q2. Create the odd numbers from 1 to 19, with 19 included.

Q3. Create 0, 5, 10, 15, … up to 50, with 50 included.

Q4. Guess what torch.arange(10, 0, -2) gives, then run it to check.

In [ ]:
roll_no = torch.arange(1,31)
print(roll_no)
print(roll_no.shape)

odd_num = torch.arange(1,20,2)
print(odd_num)

five_gap = torch.arange(0,51,5) 
print(five_gap)

torch.arange(10, 0, -2) # create numbers from 10 down to, but not including, 0, jumping by -2

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])
torch.Size([30])
tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])


tensor([10,  8,  6,  4,  2])

- `torch.zeros_like(x)` creates a tensor of zeros with the same shape as `x`
- `torch.ones_like(x)` creates a tensor of ones with the same shape as `x`
- The shape is read from the existing tensor, so there's no need to type it
- They also copy the number type (whole numbers or decimals) of the original
- Useful when two tensors must have the same shape, e.g. for `*`

Q1. Create a random tensor with shape (2, 4). Use zeros_like to make a zeros tensor of the same shape. Print both shapes to check that they match.

Q2. Create a tiny random image of size (2, 2, 3). Use ones_like to make a matching ones tensor. Multiply the two together. Is the result the same as the original image?

Q3. Create torch.arange(1, 6), then use ones_like on it. Also create torch.ones(5). Print both. What's different about how they look?



In [ ]:
# Q1: zeros and ones with the same shape as a random tensor
rand_tensor = torch.rand(2, 4)             # create a 2x4 tensor of random numbers
zero_same = torch.zeros_like(rand_tensor)  # create zeros with the same shape as rand_tensor
one_same = torch.ones_like(rand_tensor)    # create ones with the same shape as rand_tensor
print(rand_tensor.shape)                   # size of the original tensor
print(zero_same.shape)                     # size of the zeros copy, to confirm it matches

# Q2: multiply a tiny image by a matching ones tensor
tiny_image = torch.rand(2, 2, 3)           # create a random 2x2 colour image
one_like = torch.ones_like(tiny_image)     # create ones with the same shape as the image
print(tiny_image)                          # display the original image
print(tiny_image * one_like)               # multiply each number by 1, leaving the image unchanged

# Q3: compare ones_like with torch.ones
new = torch.arange(1, 6)                   # create whole numbers from 1 up to, but not including, 6
copy = torch.ones_like(new)                # create ones with the same shape and number type as new
print(copy)                                # display ones as whole numbers
print(torch.ones(5))                       # display ones created directly, as decimals


torch.Size([2, 4])
torch.Size([2, 4])
tensor([[[0.2259, 0.9984, 0.1811],
         [0.1664, 0.2496, 0.0747]],

        [[0.8437, 0.9809, 0.3239],
         [0.2628, 0.5446, 0.4273]]])
tensor([[[0.2259, 0.9984, 0.1811],
         [0.1664, 0.2496, 0.0747]],

        [[0.8437, 0.9809, 0.3239],
         [0.2628, 0.5446, 0.4273]]])
tensor([1, 1, 1, 1, 1])
tensor([1., 1., 1., 1., 1.])


- Every tensor has a datatype, checked with `.dtype`
- `int` = whole numbers (counting); `float` = decimal numbers (measuring)
- A dot in the output (e.g. `1.`) means the tensor is a float
- The number in the name (e.g. 32, 64) is how many bits of memory each number uses
- Whole-number inputs default to `torch.int64`
- Decimal inputs, `zeros`, `ones` and `rand` default to `torch.float32`
- Neural networks mainly work in `torch.float32`
- A tensor has one dtype for all its numbers; one decimal makes the whole tensor float

Q1. What's the dtype of torch.arange(0, 10)?

Q2. What's the dtype of torch.rand(2, 3)? Why do you think it has to be a float?

Q3. What's the dtype of torch.tensor([1, 2, 3.5])? (Only one of the numbers is a decimal.) How does it print?

Q4. What's the dtype of torch.zeros_like(torch.arange(5))?



In [27]:
arange_datatype = torch.arange(0,10)
print(arange_datatype.dtype)

random_datatype = torch.rand(2,3)
print(random_datatype.dtype)

tensor_datatype = torch.tensor([1,2,3.5])
print(tensor_datatype.dtype)

zeros_datatype = torch.zeros_like(torch.arange(5))
print(zeros_datatype.dtype)

torch.int64
torch.float32
torch.float32
torch.int64




- Set the datatype when creating a tensor with `dtype=`
- `dtype=` works with `torch.tensor`, `zeros`, `ones`, `rand`, `arange`, etc.
- `torch.float16`: 2 bytes per number, least exact, fastest, least memory
- `torch.float32`: 4 bytes per number, the default and the usual balance
- `torch.float64`: 8 bytes per number, most exact, slowest, most memory
- More bits = more precision but more memory and slower calculations
- float16 is used to speed up large models; float32 is the standard choice
No label + dots means float32.
No label + no dots means int64.
A dtype= label means it's something else, and the label tells you exactly what.

Q1. Create torch.tensor([1, 2, 3]) as float32 using dtype=. How does it print?

Q2. Create torch.zeros(2, 3) with float16. Check its dtype.

Q3. Store 2.71828182 in float16 and in float64, and print both using .item(). Which one is closer to what you typed?

Q4. Create torch.arange(0, 5) with dtype=torch.float32. What changes in how it prints, compared with the default?



In [38]:
# Q1: whole numbers stored as float32
arr = torch.tensor([1, 2, 3], dtype=torch.float32)             # create a tensor of whole numbers stored as 32-bit decimals
print(arr)                                                     # display the tensor

# Q2: zeros stored as float16
arr1 = torch.zeros(2, 3, dtype=torch.float16)                  # create a 2x3 tensor of zeros stored as 16-bit decimals
print(arr1.dtype)                                              # the datatype of the tensor

# Q3: compare precision of float16 and float64
float_16 = torch.tensor([2.71828182], dtype=torch.float16)     # store the number as a 16-bit decimal
print(float_16.item())                                         # display the stored value as a plain number
float_64 = torch.tensor([2.71828182], dtype=torch.float64)     # store the number as a 64-bit decimal
print(float_64.item())                                         # display the stored value as a plain number

# Q4: arange with and without a float dtype
arr3 = torch.arange(0, 5, dtype=torch.float32)                 # create numbers 0 to 4 as 32-bit decimals
print(arr3)                                                    # display the tensor
arr4 = torch.arange(0, 5)                                      # create numbers 0 to 4 as whole numbers (default)
print(arr4)                                                    # display the tensor

tensor([1., 2., 3.])
torch.float16
2.71875
2.71828182
tensor([0., 1., 2., 3., 4.])
tensor([0, 1, 2, 3, 4])


- `tensor.type(new_dtype)` creates a new tensor with the new datatype
- `tensor.to(new_dtype)` does the same thing
- The original tensor is unchanged unless you store the result back into it
- Converting float to int cuts off the decimal part; it does not round
- Mixing dtypes in `*` gives a result in the more precise type
- The 3 most common PyTorch errors: wrong datatype, wrong shape, wrong device
- Check them with `.dtype`, `.shape` and `.device`

Q1. Create torch.tensor([1.9, 2.5, 3.1]) and convert it to int64 with .type(). Guess first: will you get [2, 2, 3] or [1, 2, 3]?

Q2. Create torch.arange(0, 5) and convert it to float32. Print it. What changes?

Q3. Create a float32 tensor. Run .type(torch.float16) on it, but don't store the result in a variable. Then print the original's dtype. Did it change? Why?

Q4. Multiply a float16 tensor by a float32 tensor of the same shape. What's the dtype of the result?

In [41]:
arr = torch.tensor([1.9,2.5,3.1])
print(arr.dtype)
print(arr)
new_arr = arr.type(torch.int64)
print(new_arr)

range =torch.arange(0,5)
print(range, range.dtype)
new_range = range.type(torch.float32)
print(new_range)

data1 = torch.tensor([1,2,3],dtype=torch.float16)
data2 = torch.tensor([3,4,5], dtype=torch.float32)
ans = data1 * data2
print(ans.dtype)

x = torch.tensor([1.5, 2.5])     # create a float32 tensor
x.type(torch.float16)            # create a float16 copy, but don't store it anywhere
print(x.dtype)                   # still torch.float32

torch.float32
tensor([1.9000, 2.5000, 3.1000])
tensor([1, 2, 3])
tensor([0, 1, 2, 3, 4]) torch.int64
tensor([0., 1., 2., 3., 4.])
torch.float32
torch.float32


- Attributes are information a tensor stores about itself
- `.dtype`: the datatype of the numbers
- `.shape` (or `.size()`): the size along each dimension
- `.device`: where the tensor is stored; `cpu` by default, `cuda` for a GPU
- These three match the 3 most common errors: wrong datatype, wrong shape, wrong device
- When something breaks, check `.dtype`, `.shape` and `.device` first
- f-strings (`f"text {value}"`) insert values into text for labelled printing

Q1. Create a tensor of ones with shape (2, 3, 4) as float16. Print its dtype, shape and device using f-strings.

Q2. For torch.arange(0, 10), predict its dtype, shape and device before running, then check.

Q3. Make an "info card" for a random image tensor of size (32, 32, 3): print its dtype, shape, device and ndim, one per line, each labelled with an f-string.

In [42]:
# Q1: ones of shape (2, 3, 4) as float16
data = torch.ones(2, 3, 4, dtype=torch.float16)   # create a 2x3x4 tensor of ones stored as 16-bit decimals
print(f"Datatype: {data.dtype}")                  # print the datatype with a label
print(f"Shape: {data.shape}")                     # print the shape with a label
print(f"Device: {data.device}")                   # print the device with a label

# Q2: attributes of an arange tensor
info = torch.arange(0, 10)                        # create whole numbers from 0 up to, but not including, 10
print(f"Datatype: {info.dtype}")                  # print the datatype with a label
print(f"Shape: {info.shape}")                     # print the shape with a label
print(f"Device: {info.device}")                   # print the device with a label

# Q3: info card for a random image
info_card = torch.rand(32, 32, 3)                 # create a random image: height, width, colour channels
print(f"Datatype: {info_card.dtype}")             # print the datatype with a label
print(f"Shape: {info_card.shape}")                # print the shape with a label
print(f"Device: {info_card.device}")              # print the device with a label
print(f"Dimensions: {info_card.ndim}")            # print the number of dimensions with a label

Datatype: torch.float16
Shape: torch.Size([2, 3, 4])
Device: cpu
Datatype: torch.int64
Shape: torch.Size([10])
Device: cpu
Datatype: torch.float32
Shape: torch.Size([32, 32, 3])
Device: cpu
Dimensions: 3
